### ISSUE TITLE
How to run the example?

### ISSUE THREAD

**Issue by kristianmandrup** [Sebmaster/racer-example#4]
I finally got around to wanting to see this example running and polishing it up with some refactoring and adding validation and authorization logic etc. However, having trouble running it...

The README is very brief on this.

```
$ node app.js
connect.multipart() will be removed in connect 3.0
visit https://github.com/senchalabs/connect/wiki/Connect-3.0 for alternatives
connect.limit() will be removed in connect 3.0
```

```
$ redis-server
[20051] 16 Nov 11:38:18.628 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
[20051] 16 Nov 11:38:18.632 * Max number of open files set to 10032
[20051] 16 Nov 11:38:18.632 # Opening port 6379: bind: Address already in use
```

```
$ mongod
Sat Nov 16 11:41:30 [initandlisten] MongoDB starting : pid=20086 port=27017 dbpath=/usr/local/var/mongodb 64-bit host=kristiadrupsair
Sat Nov 16 11:41:30 [initandlisten]
Sat Nov 16 11:41:30 [initandlisten] ** WARNING: soft rlimits too low. Number of files is 256, should be at least 1000
Sat Nov 16 11:41:30 [initandlisten] db version v2.2.3, pdfile version 4.5
Sat Nov 16 11:41:30 [initandlisten] git version: f570771a5d8a3846eb7586eaffcf4c2f4a96bf08
Sat Nov 16 11:41:30 [initandlisten] build info: Darwin bs-osx-106-x86-64-1.local 10.8.0 Darwin Kernel Version 10.8.0: Tue Jun  7 16:33:36 PDT 2011; root:xnu-1504.15.3~1/RELEASE_I386 i386 BOOST_LIB_VERSION=1_49
Sat Nov 16 11:41:30 [initandlisten] options: { bind_ip: "127.0.0.1", config: "/usr/local/etc/mongod.conf", dbpath: "/usr/local/var/mongodb" }
Sat Nov 16 11:41:30 [initandlisten] exception in initAndListen: 10310 Unable to lock file: /usr/local/var/mongodb/mongod.lock. Is a mongod instance already running?, terminating
```

So both mongod and redis db servers are clearly running locally.

I go to `http://localhost:8081/` enter a value in the input like hello and press ENTER or submit and nothing happens :(

I made a small change in the code to use the local mongo and redis databases. Shouldn't this work? What am I missing? Please update the README to give more details for running it. Thanks Seb :)

``` javascript
var racer = require('racer');
var express = require('express');

var app = express();
var http = require('http');
var server = http.createServer(app);

var livedb_mongo = require('livedb-mongo')
var livedb = livedb_mongo('localhost:27017/test?auto_reconnect', {safe:true});
var redis = require('redis-url').connect();

var store = racer.createStore({
    server: server,
    db:         livedb,
  redis:    redis
});
```

**Comment by Sebmaster** [comment]
If the node process can't connect to redis or mongo it should crash at the first call which leads me to assume this is most likely a instance of #2.

**Comment by kristianmandrup** [comment]
I tried changing the dependencies, using the racer todo example as a template:

```
"dependencies": {
    "racer": "0.5.x",
    "express": "~3.2.3",
    "coffeeify": "~0.4.0",
    "racer-browserchannel": "~0.1.0",
    "livedb-mongo": "~0.1.2",
    "redis": "~0.8.3",
    "redis-url": "x"
}
```

taken from https://github.com/codeparty/racer/blob/master/examples/todos/package.json

then after `npm install`

```
$ node app.js

/Users/kmandrup/private/angular-projects/racer-angular-todo/node_modules/racer/node_modules/share/node_modules/livedb/lib/index.js:81
    throw new Error('Missing or invalid snapshot db');
          ^
Error: Missing or invalid snapshot db
    at new exports.client (/Users/kmandrup/private/angular-projects/racer-angular-todo/node_modules/racer/node_modules/share/node_modules/livedb/lib/index.js:81:11)
    at Object.exports.client (/Users/kmandrup/private/angular-projects/racer-angular-todo/node_modules/racer/node_modules/share/node_modules/livedb/lib/index.js:75:41)
    at new ShareInstance (/Users/kmandrup/private/angular-projects/racer-angular-todo/node_modules/racer/node_modules/share/lib/server/index.js:23:27)
    at Object.exports.createClient (/Users/kmandrup/private/angular-projects/racer-angular-todo/node_modules/racer/node_modules/share/lib/server/index.js:115:10)
    at new Store (/Users/kmandrup/private/angular-projects/racer-angular-todo/node_modules/racer/lib/Store.js:15:35)
    at Racer.createStore (/Users/kmandrup/private/angular-projects/racer-angular-todo/node_modules/racer/lib/Racer.server.js:8:15)
    at Object.<anonymous> (/Users/kmandrup/private/angular-projects/racer-angular-todo/app.js:12:19)
```

So now, `racer.createStore` fails, perhaps due to the livedb version being incompatible?? strange!

**Comment by mgan59** [comment]
Fixed this issue with snapshot and livedb out of date - https://github.com/codeparty/racer/issues/161  awaiting for pull-request to be accepted.

**Comment by Sebmaster** [comment]
Nice, thank you very much @mgan59! I'll close this bug then.

**Comment by kristianmandrup** [comment]
Perfect :)
